version: "3.9"

services:
  fastapi:
    build:
      context: ./fast-api
    container_name: ollama-api
    ports:
      - "8000:8000"
    env_file:
      - ./fast-api/.env
    volumes:
      - ./fast-api:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - storage-service

  storage-service:
    build:
      context: ./chat-storage-service
    container_name: storage-api
    ports:
      - "8001:8001"
    env_file:
      - ./chat-storage-service/.env
    volumes:
      - ./chat-storage-service:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ollama

  frontend:
    build:
      context: ./ollama-chat
    container_name: frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./ollama-chat:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - fastapi


volumes:
  mongo-data:
